### ISSUE TITLE
Playlist does not update

### ISSUE THREAD

**Issue by 9dogs** [ethanzohar/discoverify#10]
Hey! Thank you very much for the great service.
Unfortunately, it stopped working - "Your playlist was last updated 589 hours ago". I tried to Unsubscribe and Subscribe again, as well as disconnecting and reconnecting my Spotify account.
What information can I provide to help to debug the issue?

**Comment by eriksss** [comment]
Same problem here...

**Comment by ethanzohar** [comment]
@9dogs @eriksss could you send me your Spotify ID's. I will force update your playlists and check to see if the Spotify API is throwing errors for your accounts.

**Comment by 9dogs** [comment]
@ethanzohar, sure, my id is `214wgkibhljgr6q6nimmkcj3q`

**Comment by ethanzohar** [comment]
@9dogs I attempted to force update your playlist and I get the following error from the Spotify API:
`{ error: { status: 401, message: 'Invalid access token' } }`

To fix this we will need to reset your access token. I have already gone ahead and completely deleted your user from the Discoverify service. You will need to go to https://www.spotify.com/us/account/apps/ and remove access to Discoverify, then try to resubscribe to Discoverify at https://discoverifymusic.com/

Let me know when you do this and I can check the logs to make sure everything went smoothly for you.

**Comment by ethanzohar** [comment]
@eriksss If you send me your Spotify ID I can check the error and reset your account as well if needed.

**Comment by eriksss** [comment]
Sure Please, could you reset my account?
Id: u88szdUpR66oV2N537odvA

**Comment by 9dogs** [comment]
@ethanzohar, it works now, many thanks! 
Is there a way to fix this issue from the user side if it happens again? Initially, I revoked access to your app as well, but it didn't fix it: after re-logging into your app through Spotify and confirming access permissions, I didn't get the "Configure your playlist" wizard, I skipped straight to "Your playlist was last updated 589 hours ago". It must be to do with you deleting us from Discoverify's DB.

**Comment by eriksss** [comment]
@ethanzohar it keeps saying:
Your playlist was last updated 3609 hours ago…

**Comment by ethanzohar** [comment]
@eriksss there is no user signed up with Discoverify with that Spotify ID, could you send me your username instead? You can find exactly what is stored for your username at https://www.spotify.com/us/account/overview/

You playlist will still say 3000+ hours until I can find your user and reset it.

**Comment by ethanzohar** [comment]
@9dogs I think I understand how and why this situation occurs. 

When a user tries to make any request to Discoverify (such as unsubscribing) I first validate that they are who they say they are (so that someone else cannot unsubscribe for you). I do this by cross referencing the user you say you are with who Spotify says your access token belongs too. If you revoke access to Discoverify before unsubscribing, the Spotify API will not allow me to verify your user, so I always reject the request to unsubscribe.

I do not think that there is a possible fix from the users' perspective since once you disable Spotify access to the app you are completely locked out, even if you try to reenable it.

The fix from the service's perspective:
Every night the service will update your playlist, if the API returns an invalid access token error while performing the playlist update I will delete the user since they will never be able to regain access to their account in its current state.

This fix will mean that the "corrupted" accounts will be removed every 24 hours, so the user who disabled access to Discoverify will be able to resubscribe in 24 hours. It is still not perfect since there is a long wait time to resubscribe, but it will work until I can find a better solution for verify a user is who they say they are without the Spotify API.

**Comment by ethanzohar** [comment]
@eriksss I have just gone ahead and wiped all "corrupted" users. You should not be able to resubscribe 🚀 🎉

**Comment by ethanzohar** [comment]
@eriksss @9dogs I have just pushed a fix so that I clean corrupted accounts during the playlist update, this means that this issue should not happen to anyone else (and if it if does it will be resolved within 24 hours)!!!!

Thank you both for bringing this to my attention ❤️

**Comment by ethanzohar** [comment]
Closing since issue has been resolved

**Comment by shaleenb** [comment]
Hi. My playlist hasn't updated for more than 24 hours.
